apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
      - name: my-api
        image: clmgoregistry.azurecr.io/leggo:1.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mysecret
---
apiVersion: v1
kind: Service
metadata: 
  name: my-api
spec: 
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: my-api
